# Generated by Django 6.0.4 on 2026-04-30 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=10, null=True)),
                ("color", models.CharField(blank=True, max_length=20, null=True)),
                ("requirement", models.IntegerField()),
                ("level", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "db_table": "Badge",
            },
        ),
        migrations.CreateModel(
            name="DashboardStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=50)),
                ("trend", models.CharField(blank=True, max_length=20, null=True)),
                ("color", models.CharField(blank=True, max_length=30, null=True)),
                ("subtext", models.CharField(blank=True, max_length=100, null=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Dashboard Stat",
                "verbose_name_plural": "Dashboard Stats",
                "db_table": "DashboardStat",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="FeaturedPromo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("promo_type", models.CharField(blank=True, max_length=50, null=True)),
                ("badge_label", models.CharField(blank=True, max_length=50, null=True)),
                ("btn_text", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="promos/"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Featured Promo",
                "verbose_name_plural": "Featured Promos",
                "db_table": "FeaturedPromo",
            },
        ),
        migrations.CreateModel(
            name="GamificationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login_points", models.IntegerField(default=10)),
                ("review_base", models.IntegerField(default=25)),
                ("review_bonus", models.IntegerField(default=50)),
                ("review_min_char", models.IntegerField(default=100)),
                ("purchase_rate", models.FloatField(default=2.0)),
                ("purchase_max", models.IntegerField(default=500)),
                ("signup_bonus", models.IntegerField(default=50)),
            ],
            options={
                "verbose_name": "Gamification Config",
                "verbose_name_plural": "Gamification Config",
                "db_table": "GamificationConfig",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
                "db_table": "Genre",
            },
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("min_points", models.IntegerField()),
                ("max_points", models.IntegerField()),
                ("icon", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "verbose_name": "Rank",
                "verbose_name_plural": "Ranks",
                "db_table": "Rank",
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("cost", models.IntegerField()),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="rewards/"),
                ),
                (
                    "reward_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("discount", "Discount"),
                            ("freebie", "Freebie"),
                            ("exclusive", "Exclusive"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("badge", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Reward",
                "verbose_name_plural": "Rewards",
                "db_table": "Reward",
            },
        ),
        migrations.CreateModel(
            name="SaleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("percentage", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Sale Event",
                "verbose_name_plural": "Sale Events",
                "db_table": "SaleEvent",
            },
        ),
        migrations.CreateModel(
            name="SalesPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("label", models.CharField(max_length=20)),
                ("total_height", models.IntegerField()),
                ("fill_height", models.IntegerField()),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Sales Performance",
                "verbose_name_plural": "Sales Performances",
                "db_table": "SalesPerformance",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="CuratedConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("limit", models.IntegerField(default=4)),
                (
                    "display_genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curated_configs",
                        to="core.genre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curated Config",
                "verbose_name_plural": "Curated Configs",
                "db_table": "CuratedConfig",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pages", models.IntegerField()),
                ("rating", models.FloatField(default=0.0)),
                (
                    "cover_img",
                    models.ImageField(blank=True, null=True, upload_to="covers/"),
                ),
                (
                    "published_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("sales", models.IntegerField(default=0)),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="books",
                        to="core.genre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "db_table": "Book",
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(max_length=20, unique=True)),
                ("sku", models.CharField(max_length=20, unique=True)),
                ("stock", models.IntegerField(default=0)),
                ("max_stock", models.IntegerField(default=100)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="core.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory",
                "verbose_name_plural": "Inventories",
                "db_table": "Inventory",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("uname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("customer", "Customer"),
                            ("staff", "Staff"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("points", models.IntegerField(default=0)),
                ("readings", models.IntegerField(default=0)),
                ("reviews", models.IntegerField(default=0)),
                ("join_date", models.DateField(auto_now_add=True)),
                ("last_login", models.DateField(blank=True, null=True)),
                ("last_active", models.DateField(blank=True, null=True)),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="core.rank",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "User",
            },
        ),
        migrations.CreateModel(
            name="RewardRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points_spent", models.IntegerField()),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="core.reward",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reward Redemption",
                "verbose_name_plural": "Reward Redemptions",
                "db_table": "RewardRedemption",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=150)),
                ("rating", models.IntegerField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_reviews",
                        to="core.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_reviews",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "db_table": "Review",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("customer_name", models.CharField(max_length=150)),
                ("book_title", models.CharField(max_length=255)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="core.book",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "db_table": "Order",
            },
        ),
        migrations.CreateModel(
            name="UserBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("bought", "Bought"),
                            ("rented", "Rented"),
                            ("gifted", "Gifted"),
                        ],
                        max_length=10,
                    ),
                ),
                ("acquired_at", models.DateField(auto_now_add=True)),
                ("progress", models.IntegerField(default=0)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="core.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Book",
                "verbose_name_plural": "User Books",
                "db_table": "UserBook",
            },
        ),
        migrations.CreateModel(
            name="SaleDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_discounts",
                        to="core.genre",
                    ),
                ),
                (
                    "sale_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="core.saleevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sale Discount",
                "verbose_name_plural": "Sale Discounts",
                "db_table": "SaleDiscount",
                "unique_together": {("sale_event", "genre")},
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awarded_to",
                        to="core.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Badge",
                "verbose_name_plural": "User Badges",
                "db_table": "UserBadge",
                "unique_together": {("user", "badge")},
            },
        ),
    ]
