# Generated by Django 6.0.4 on 2026-05-03 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_book_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="genre",
        ),
    ]
