# Generated by Django 6.0.4 on 2026-05-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_book_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="mastery_target",
            field=models.IntegerField(default=10),
        ),
    ]
